from pathlib import Path

p = Path('src/app/page.tsx')
s = p.read_text()
marker = '  // ---------------------------------------------------------\n  // Live match resume\n  // ---------------------------------------------------------\n'
handlers = '''  async function removePlayerFromCurrentRoster(playerId: string, playerName: string) {\n    if (!selectedTeamId) return;\n    if (!window.confirm(`Remove "${playerName}" from this team's current roster?\\n\\nThe global player and historical match data will remain.`)) return;\n    try {\n      setError("");\n      const response = await fetch(`/api/teams/${selectedTeamId}/players`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ playerId }) });\n      const data = await response.json();\n      if (!response.ok) throw new Error(data?.error || "Failed to remove player from roster.");\n      await loadTeamPlayers(selectedTeamId);\n      if (selectedTournament) await refreshSelectedTournament(selectedTournament.id);\n    } catch (err) {\n      console.error(err);\n      setError(err instanceof Error ? err.message : "Failed to remove player from roster.");\n    }\n  }\n\n  async function removeTeamFromCurrentTournament(teamId: string, teamName: string) {\n    if (!selectedTournament) return;\n    if (!window.confirm(`Remove "${teamName}" from ${selectedTournament.name}?\\n\\nThe global team, players and historical match data will remain.`)) return;\n    try {\n      setError("");\n      const response = await fetch(`/api/tournaments/${selectedTournament.id}/teams`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ teamId }) });\n      const data = await response.json();\n      if (!response.ok) throw new Error(data?.error || "Failed to remove team from tournament.");\n      if (selectedTeamId === teamId) { setSelectedTeamId(null); setTeamPlayers([]); }\n      await refreshSelectedTournament(selectedTournament.id);\n    } catch (err) {\n      console.error(err);\n      setError(err instanceof Error ? err.message : "Failed to remove team from tournament.");\n    }\n  }\n\n'''
if 'async function removePlayerFromCurrentRoster' not in s:
    if marker not in s: raise SystemExit('live match marker not found')
    s = s.replace(marker, handlers + marker, 1)
old_team = '''                      <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-800 text-lg">\n                        {String.fromCodePoint(0x1F3CF)}\n                      </div>'''
new_team = '''                      <div className="flex shrink-0 items-center gap-2">\n                        <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-800 text-lg">\n                          {String.fromCodePoint(0x1F3CF)}\n                        </div>\n                        <button type="button" title="Remove team from this tournament" aria-label={`Remove ${tournamentTeam.team.name} from this tournament`} onClick={(event) => { event.stopPropagation(); void removeTeamFromCurrentTournament(tournamentTeam.team.id, tournamentTeam.team.name); }} className="flex h-9 w-9 items-center justify-center rounded-xl border border-red-500/30 bg-red-500/10 text-lg font-bold text-red-400 transition hover:bg-red-500/20">−</button>\n                      </div>'''
if old_team in s:
    s = s.replace(old_team, new_team, 1)
old_player = '''                        <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-800 text-lg">\n                          PLAYER\n                        </div>'''
new_player = '''                        <button type="button" title="Remove player from current roster" aria-label={`Remove ${membership.player.name} from current roster`} onClick={() => void removePlayerFromCurrentRoster(membership.player.id, membership.player.name)} className="flex h-10 w-10 items-center justify-center rounded-xl border border-red-500/30 bg-red-500/10 text-xl font-bold text-red-400 transition hover:bg-red-500/20">−</button>'''
if old_player in s:
    s = s.replace(old_player, new_player, 1)
p.write_text(s)
