from pathlib import Path

p = Path('src/app/page.tsx')
s = p.read_text(encoding='utf-8-sig')

old_resume = '''      setLiveBowlerAId(\n        currentInnings.currentBowlerAId ?? "",\n      );\n      setLiveBowlerBId(\n        currentInnings.currentBowlerBId ?? "",\n      );\n      setLiveBowlerId(\n        currentInnings.currentBowlerAId ??\n          currentInnings.currentBowlerBId ??\n          "",\n      );\n      setLivePreviousBowlerAId(\n        currentInnings.previousOverBowlerAId ?? "",\n      );\n      setLivePreviousBowlerBId(\n        currentInnings.previousOverBowlerBId ?? "",\n      );\n      setLiveDeliveryCount(\n        Number(currentInnings.legalBalls ?? 0) % 6,\n      );\n      setLiveCurrentOver(\n        Math.floor(\n          Number(currentInnings.legalBalls ?? 0) / 6,\n        ) + 1,\n      );\n      setLiveCurrentBall(\n        (Number(currentInnings.legalBalls ?? 0) % 6) + 1,\n      );\n'''

new_resume = '''      const resumedDeliveries = Array.isArray(currentInnings.deliveries)\n        ? currentInnings.deliveries\n        : [];\n      const lastResumedDelivery =\n        resumedDeliveries[resumedDeliveries.length - 1] ?? null;\n      const currentOverNumberFromData =\n        lastResumedDelivery?.overNumber ?? 1;\n      const currentOverDeliveriesFromData =\n        resumedDeliveries.filter(\n          (delivery: { overNumber: number }) =>\n            delivery.overNumber === currentOverNumberFromData,\n        );\n      const currentOverLegalBallsFromData =\n        currentOverDeliveriesFromData.filter(\n          (delivery: { isLegal: boolean }) => delivery.isLegal,\n        ).length;\n\n      const observedCurrentOverBowlers = [\n        ...new Set(\n          currentOverDeliveriesFromData\n            .map((delivery: { bowlerId: string }) => delivery.bowlerId)\n            .filter(Boolean),\n        ),\n      ];\n\n      const resumedBowlerAId =\n        observedCurrentOverBowlers[0] ??\n        currentInnings.currentBowlerAId ??\n        currentInnings.currentBowlerBId ??\n        \"\";\n      const resumedBowlerBId =\n        observedCurrentOverBowlers[1] ??\n        currentInnings.currentBowlerBId ??\n        (resumedBowlerAId !== currentInnings.currentBowlerAId\n          ? currentInnings.currentBowlerAId\n          : \"\") ??\n        \"\";\n\n      setLiveBowlerAId(resumedBowlerAId);\n      setLiveBowlerBId(resumedBowlerBId);\n\n      const resumedCurrentBowlerId =\n        bowlingMode === \"DOUBLE\" &&\n        !liveOddOvers &&\n        resumedBowlerAId &&\n        resumedBowlerBId\n          ? currentOverDeliveriesFromData.length % 2 === 0\n            ? resumedBowlerAId\n            : resumedBowlerBId\n          : resumedBowlerAId || resumedBowlerBId;\n\n      setLiveBowlerId(resumedCurrentBowlerId);\n      setLivePreviousBowlerAId(\n        currentInnings.previousOverBowlerAId ?? \"\",\n      );\n      setLivePreviousBowlerBId(\n        currentInnings.previousOverBowlerBId ?? \"\",\n      );\n      setLiveDeliveryCount(currentOverDeliveriesFromData.length);\n      setLiveCurrentOver(\n        lastResumedDelivery && currentOverLegalBallsFromData < 6\n          ? currentOverNumberFromData\n          : currentOverNumberFromData + 1,\n      );\n      setLiveCurrentBall(\n        lastResumedDelivery && currentOverLegalBallsFromData < 6\n          ? currentOverLegalBallsFromData + 1\n          : 1,\n      );\n'''

if old_resume not in s:\n    raise SystemExit('resume block not found')\ns = s.replace(old_resume, new_resume, 1)\n\nold_layout = '''                  <div className="mt-2 grid grid-cols-1 gap-2 sm:grid-cols-3">\n                    {recordButton("MORE RUNS", "bg-slate-800 text-white hover:bg-slate-900 col-span-1", () => openCustomDeliveryPanel())}\n                  </div>\n                  <button type="button" disabled={liveLoading || liveInningsComplete || !liveBowlerId} onClick={() => openWicketPanel()} className="mt-2 h-20 w-full rounded-xl bg-red-500 text-lg font-black text-white hover:bg-red-600 disabled:opacity-40 [color-scheme:dark]">WICKET</button>\n'''

new_layout = '''                  <div className="mt-2 grid grid-cols-3 gap-2">\n                    <button\n                      type="button"\n                      disabled={liveLoading || liveInningsComplete || !liveBowlerId}\n                      onClick={() => openWicketPanel()}\n                      className="col-span-2 h-20 rounded-xl bg-red-500 text-lg font-black text-white hover:bg-red-600 disabled:opacity-40 [color-scheme:dark]"\n                    >\n                      WICKET\n                    </button>\n                    {recordButton(\n                      "MORE RUNS",\n                      "col-span-1 bg-slate-800 text-white hover:bg-slate-900 h-20",\n                      () => openCustomDeliveryPanel(),\n                    )}\n                  </div>\n'''

if old_layout not in s:\n    raise SystemExit('delivery layout block not found')\ns = s.replace(old_layout, new_layout, 1)\n\np.write_text(s, encoding='utf-8')\nprint('resume bowling and delivery layout patched')\n