from pathlib import Path
p=Path('src/app/page.tsx')
s=p.read_text()
repls=[]
repls.append(('''  const [wicketType, setWicketType] =\n    useState("BOWLED");\n''','''  const [wicketType, setWicketType] =\n    useState("BOWLED");\n  const [fielderId, setFielderId] = useState("");\n  const [liveWicketDetailsByPlayerId, setLiveWicketDetailsByPlayerId] = useState<Record<string, { type: string; bowlerId: string | null; fielderId: string | null }>>({});\n'''))
repls.append(('''    wicket: { type: string; dismissedPlayerId: string; bowlerId: string | null } | null;\n''','''    wicket: { type: string; dismissedPlayerId: string; bowlerId: string | null; fielderId?: string | null } | null;\n'''))
repls.append(('''    setReplacementPlayerId("");\n    setWicketType(extraType ? "RUN_OUT" : "BOWLED");\n''','''    setReplacementPlayerId("");\n    setFielderId("");\n    setWicketType(extraType ? "RUN_OUT" : "BOWLED");\n'''))
repls.append(('''    dismissedPlayerId?: string;\n    replacementPlayerId?: string;\n  }) {\n''','''    dismissedPlayerId?: string;\n    replacementPlayerId?: string;\n    fielderId?: string;\n  }) {\n'''))
repls.append(('''      setLiveWickets(\n        Number(\n''','''      if (input.isWicket && input.dismissedPlayerId) {\n        setLiveWicketDetailsByPlayerId((current) => ({\n          ...current,\n          [input.dismissedPlayerId!]: {\n            type: input.wicketType ?? "OUT",\n            bowlerId: liveBowlerId || null,\n            fielderId: input.fielderId ?? null,\n          },\n        }));\n      }\n\n      setLiveWickets(\n        Number(\n'''))
repls.append(('''    const recordButton = (label: string, className: string, action: () => void, disabled = false) => (\n''','''    const liveDismissalText = (playerId: string) => {\n      const detail = liveWicketDetailsByPlayerId[playerId];\n      if (!detail) return "OUT";\n      const playerName = (id: string | null) =>\n        liveBowlingPlayers.find((player) => player.id === id)?.name ?? "Player";\n      const bowler = playerName(detail.bowlerId);\n      const fielder = detail.fielderId ? playerName(detail.fielderId) : "";\n      switch (detail.type) {\n        case "BOWLED": return `b ${bowler}`;\n        case "CAUGHT": return fielder ? `c ${fielder}   b ${bowler}` : `c b ${bowler}`;\n        case "LBW": return `lbw b ${bowler}`;\n        case "RUN_OUT": return fielder ? `run out (${fielder})` : "run out";\n        case "STUMPED": return fielder ? `st ${fielder}   b ${bowler}` : `st b ${bowler}`;\n        case "HIT_WICKET": return `hit wicket b ${bowler}`;\n        case "OVER_FENCE": return "over fence";\n        default: return "OUT";\n      }\n    };\n\n    const recordButton = (label: string, className: string, action: () => void, disabled = false) => (\n'''))
repls.append(('''                              <span className="truncate font-bold">{stat.player.name}{stat.player.id === liveStrikerId ? " *" : ""}{stat.dismissed ? " OUT" : ""}</span>\n                            </div>''','''                              <div className="min-w-0">\n                                <span className="block truncate font-bold">{stat.player.name}{stat.player.id === liveStrikerId ? " *" : ""}{stat.dismissed ? " OUT" : ""}</span>\n                                <span className="block truncate whitespace-pre text-[9px] text-slate-400">{stat.dismissed ? liveDismissalText(stat.player.id) : "NOT OUT"}</span>\n                              </div>\n                            </div>'''))
repls.append(('''setReplacementPlayerId(""); }} className="h-12 w-full rounded-lg border border-slate-700''','''setReplacementPlayerId(""); setFielderId(""); }} className="h-12 w-full rounded-lg border border-slate-700'''))
repls.append(('''</select></div>\n                {wicketType === "RUN_OUT" && (''','''</select></div>\n                {(wicketType === "CAUGHT" || wicketType === "RUN_OUT" || wicketType === "STUMPED") && (\n                  <div>\n                    <label htmlFor="fielderPlayer" className="mb-2 block text-sm font-semibold">{wicketType === "CAUGHT" ? "Caught by" : wicketType === "STUMPED" ? "Stumped by" : "Run out by"}</label>\n                    <select id="fielderPlayer" value={fielderId} onChange={(event) => setFielderId(event.target.value)} className="h-12 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-white [color-scheme:dark]">\n                      <option value="">Select player</option>\n                      {liveBowlingPlayers.map((player) => (\n                        <option key={player.id} value={player.id}>{player.name}</option>\n                      ))}\n                    </select>\n                  </div>\n                )}\n                {wicketType === "RUN_OUT" && ('''))
repls.append(('''disabled={!replacementPlayerId || liveLoading} onClick={() => void recordLiveDelivery({ isWicket: true, wicketType, dismissedPlayerId, replacementPlayerId, ...(pendingWicketExtraType ? { runsExtra: pendingWicketExtraRuns, extraType: pendingWicketExtraType } : {}) })}''','''disabled={!replacementPlayerId || liveLoading || ((wicketType === "CAUGHT" || wicketType === "RUN_OUT" || wicketType === "STUMPED") && !fielderId)} onClick={() => void recordLiveDelivery({ isWicket: true, wicketType, dismissedPlayerId, replacementPlayerId, ...(fielderId ? { fielderId } : {}), ...(pendingWicketExtraType ? { runsExtra: pendingWicketExtraRuns, extraType: pendingWicketExtraType } : {}) })}'''))
repls.append(('''setPendingWicketExtraRuns(0); setReplacementPlayerId(""); }} className="h-12 rounded-lg border''','''setPendingWicketExtraRuns(0); setReplacementPlayerId(""); setFielderId(""); }} className="h-12 rounded-lg border'''))
for old,new in repls:
    n=s.count(old)
    if n!=1:
        raise SystemExit(f'Marker count {n}: {old[:100]!r}')
    s=s.replace(old,new,1)
p.write_text(s)
print('patched wicket UI only')
